### ISSUE TITLE
Lazy iterator DML support for DML Options

### ISSUE THREAD

**Issue by DanBeerNebula** [aidan-harding/nebula-core#2]
Currently, the lazy iterator DML support only the all or nothing flag.

Can we add support to pass in Database.DMLOptions instead, please?

Database.DMLOptions dml = new Database.DMLOptions();

new nebc.LazySObjectIterator(newList)
                .filterT(new nebc.IsSObjectFieldEqual(Payment__c.Create_Task__c, true))
                .mapValuesT(new BuildPaymentTask(taskOwnerId))
                .doInsert(dml);

**Comment by aidan-harding** [comment]
Good shout...

Released in v0.76
