### ISSUE TITLE
Cannot find Test_Record_Generator__mdt

### ISSUE THREAD

**Issue by matcaampos** [aidan-harding/nebula-core#4]
Hi aidan, sorry for writing for you again.

If do you prefer I sended to you an invite in the linkedin.

aidan i'm have many difficults to use nebula, and i'm using the .md example.

For example:

i'm trying to use the testrecordsource like the documentation:
![image](https://user-images.githubusercontent.com/41803840/152547476-242c0ffb-5b0c-46a0-8c6c-3c024ceb0ced.png)

but the issue is that don't find the metadata:
![image](https://user-images.githubusercontent.com/41803840/152547594-66f6609e-116d-4ef6-9804-1db940fd216b.png)

but the metadata is in my org:
![image](https://user-images.githubusercontent.com/41803840/152547665-0fc946fc-6cd2-427d-9d05-562e7848f9a8.png)

**Comment by aidan-harding** [comment]
No problem with posting them here. Someone else might have the same questions and come across these discussions, so don't worry about it.

It's looking for some custom metadata records in the Test_Record_Generator__mdt type. When you ask it to make a Contact record, it looks for a Test_Record_Generator__mdt record where the SObject__c field matches, and that tells it how to make a Contact in this org.

In the docs section https://github.com/aidan-harding/nebula-core/blob/main/force-app/testRecordGenerator/TestRecordGenerator.md#importing-test-data-for-standard-objects, it tells you about how to automatically create some records for some of the standard objects. 

If you run the following in an anonymous Apex window, it will create those records for Account and Contact:

new nebc.StandardTestRecordGenerators().deploy('Account');
new nebc.StandardTestRecordGenerators().deploy('Contact');

If you do that, and then go to the Manage Records for Test_Record_Generator__mdt in the setup UI, you'll see some records. And your test should run.

The test record generator is quite an unusual way of doing things in the SF ecosystem, but it's really powerful once you're up and running.
